FROM python:3.6

RUN apt-get update && apt-get install -y git curl

WORKDIR /app

RUN git clone --branch apps https://github.com/zveridze/gallery_drf_api.git .

RUN pip install -r requirements.txt

RUN python3 manage.py migrate